adding gemma dates model
Gemma-Analytics/gemma-dbt-utils pull request #45
Opened 2021-07-05 12:40 UTC by monika-pavlova

2021-07-05 13:00 UTC, soltanianalytics requested changes
Very nice! Almost ready. Can you add a data test in the `integration_tests` project? Comparable to the fx rates one :)

2021-07-05 13:00 UTC, soltanianalytics commented on README.md
> +This model will create the table `gemma_dates` in the schema `YOUR_SCHEMA_gemma_dbt_utils`. Starting from a defined date it will create a date series with different date columns until a specified num
Request (blocking): Can you add the table name and schema as variables as well, with the `gemma_dates` and `YOUR_SCHEMA_gemma_dbt_utils` as defaults?

You can at least do the latter using variables and the `config` macro. I'm not 100% sure if the former is a good idea yet, also see [here](https://getdbt.slack.com/archives/C0VLZPLAE/p1625489807142100), but you can at least change the name using `alias` in the `config` macro. I'd say it is a good idea if the model can be referenced by the alias, and not otherwise.

2021-07-05 14:59 UTC, Dimi727 reviewed
no blocking things from my side. Just a question regarding documentation and variable useage.

Maybe you could also add some flags, like:
- `IF(EXTRACT(DAYOFWEEK FROM date) NOT IN (1,7), true, false) AS is_weekday`

What also can be useful is number of days in the current month:
* `DATE_DIFF(DATE_TRUNC(DATE_ADD(date, INTERVAL 1 MONTH), MONTH),
        DATE_TRUNC(date, MONTH), DAY) AS days_in_month`

2021-07-05 14:59 UTC, Dimi727 commented on README.md
> +
non-blocking:

small thing, required fields usually dont use default values, am I wrong? Optional strings have default values though.

So `timezone` for example should not be required because it by default sets `Europe/Berlin`, `enabled` is always false except we set it.

Required fields like `start_date` should not set any value and complain to do so to work.

And so on.

2021-07-05 15:19 UTC, jups23 commented
> Maybe you could also add some flags, like:
> 
>     * `IF(EXTRACT(DAYOFWEEK FROM date) NOT IN (1,7), true, false) AS is_weekday`

I believe it would become even clearer like this `EXTRACT(DAYOFWEEK FROM date) NOT IN (1,7) AS is_weekday`

2021-07-05 19:27 UTC, soltanianalytics commented
One more thing: Would it make sense to change the `id` column from a `serial` to the format `yyyymmdd`?

Rationale: Then the primary key is identical for the same date irrespective of start dates, which can then more easily be changed. On the flipside, you then can't just take deltas between `id`s to get number of days between dates. wdyt?

2021-07-06 11:49 UTC, monika-pavlova commented on README.md
> +
Dima, thanks for the variable suggestions! :) Added the flag and the days in month is already under `month_days`.
`EXTRACT(DAY FROM LAST_DAY(date, MONTH)) AS month_days` 
Let me know if you think of some other useful variable! :)

2021-07-07 06:29 UTC, monika-pavlova commented
Thank you all for the comments!

@soltanianalytics I do like the idea of having a primary key, which is identical for the same date irrespective of start dates. As for getting the number of days between dates, I assume they could also be calculated from the dates themselves. :/

2021-07-07 08:23 UTC, soltanianalytics approved these changes
Let's do that, then :)

Otherwise, LGTM! Feel free to merge it unless you want to make an update re the non-blocking and/or ID topics

2021-07-07 08:23 UTC, soltanianalytics commented on README.md
> +| gemma:dates:end_date | '30 day' | Optional String. Sets the `end_date` for the date series. By defaul, it's set to '30 day' |
Suggestion (non-blocking): Can you add that this is an interval relative to `current_date`?

Is obvious to us now, but might help someone down the line :)

2021-07-07 08:23 UTC, soltanianalytics commented on dbt_project.yml
> +  'gemma:dates:schema': 'gemma_dbt_utils' # overwrite to get a different default value
Question (non-blocking): Would setting this to `null` also work, then taking the project default (which would be the same)?

Background: In case we change the schema in the `dbt_project.yml` but not here, there'll otherwise be a mismatch.

2021-07-07 09:35 UTC, monika-pavlova commented on dbt_project.yml
> +  'gemma:dates:schema': 'gemma_dbt_utils' # overwrite to get a different default value
Setting it to null, defaults to the target schema defined in the `profiles.yml`, e.g. the result will be `analytics.gemma_dates`. -  see [here](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas)
If I understand correctly the config(..) in the model overwrites the specification in the `dbt_project.yml`

2021-07-07 09:35 UTC, monika-pavlova commented on dbt_project.yml
> +  'gemma:dates:schema': 'gemma_dbt_utils' # overwrite to get a different default value
The rest is implemented :)

2021-07-07 09:35 UTC, monika-pavlova commented on README.md
> +| gemma:dates:end_date | '30 day' | Optional String. Sets the `end_date` for the date series. By defaul, it's set to '30 day' |
Good point! :)

2021-07-07 10:17 UTC, soltanianalytics approved these changes

2021-07-07 10:18 UTC, soltanianalytics commented on dbt_project.yml
> +  'gemma:dates:schema': 'gemma_dbt_utils' # overwrite to get a different default value
Ha! So then it sets it to `None` instead of using the default.

Let's keep it as it

2021-07-07 10:40 UTC, soltanianalytics approved these changes

2021-07-07 10:40 UTC, merged